version: '2.18'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/university
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  postgres-data:
